import os
import requests
import io
import threading
import asyncio
import nest_asyncio
from flask import Flask
from pyrogram import Client, filters
from pyrogram.types import InlineKeyboardMarkup, InlineKeyboardButton

nest_asyncio.apply()

# --- HEALTH CHECK FOR RENDER ---
flask_app = Flask(__name__)
@flask_app.route('/')
def home(): return "AI Image Bot is Running!", 200

def run_flask():
    port = int(os.environ.get("PORT", 10000))
    flask_app.run(host='0.0.0.0', port=port)

# --- BOT CONFIGURATION ---
# Use your existing credentials
API_ID = 28300966
API_HASH = "c0a1fe56b13f260c62bc4838feb416d9"
BOT_TOKEN = "8427226244:AAG9sDCHxaQm3IcRjzQimz0MTcEmOr_dvd0"

app = Client("AIImageGenBot", api_id=API_ID, api_hash=API_HASH, bot_token=BOT_TOKEN)

# --- START COMMAND ---
@app.on_message(filters.command("start"))
async def start(client, message):
    welcome_text = (
        "🎨 **Welcome to AI Image Generator!**\n\n"
        "Simply send me a description of what you want to see, and I will create an image for you.\n\n"
        "**Example:** `A futuristic city in space` or `A cute cat wearing a crown`"
    )
    await message.reply_text(welcome_text)

# --- IMAGE GENERATION HANDLER ---
@app.on_message(filters.text & filters.private)
async def generate_image(client, message):
    prompt = message.text
    
    # Ignore commands
    if prompt.startswith("/"):
        return

    # Inform the user that processing has started
    status_msg = await message.reply_text("⏳ **Generating your AI art... Please wait.**")

    try:
        # Constructing the Pollinations AI URL
        # We encode the prompt to handle spaces and special characters
        encoded_prompt = prompt.replace(" ", "%20")
        image_url = f"https://pollinations.ai/p/{encoded_prompt}?width=1024&height=1024&seed=42&model=flux"

        # Fetch the image
        response = requests.get(image_url)
        
        if response.status_code == 200:
            # Create a bio-stream for the image
            photo = io.BytesIO(response.content)
            photo.name = "ai_image.jpg"

            # Send the photo
            await message.reply_photo(
                photo=photo,
                caption=f"✨ **Result for:** `{prompt}`\n\nGenerated by AI"
            )
            # Delete the status message
            await status_msg.delete()
        else:
            await status_msg.edit_text("❌ Sorry, I couldn't generate the image right now. Try again later.")

    except Exception as e:
        print(f"Error: {e}")
        await status_msg.edit_text("❌ Something went wrong while generating the image.")

# --- RUN THE BOT ---
if __name__ == "__main__":
    # Start Flask in background
    threading.Thread(target=run_flask, daemon=True).start()
    
    print("AI Image Bot is starting...")
    app.run()
